### ISSUE TITLE
Referencing the top level module fails - :mod:`PySide2`

### ISSUE THREAD

**Issue by altendky** [Czaki/sphinx-qt-documentation#13]
https://github.com/Czaki/sphinx-qt-documentation/blob/25d2dc15fb14a3b2b2ab45de889c2e0eabb76cd4/sphinx_qt_documentation/__init__.py#L94

```pytb
Traceback (most recent call last):
  File "/epc/repos/ssst/venv/lib/python3.9/site-packages/sphinx/events.py", line 110, in emit
    results.append(listener.handler(self.app, *args))
  File "/epc/repos/ssst/venv/lib/python3.9/site-packages/sphinx_qt_documentation/__init__.py", line 94, in missing_reference
    head, tail = target.split(".", 1)
ValueError: not enough values to unpack (expected 2, got 1)
```

This shows up cryptically through Sphinx as follows.

```
Extension error:
Handler <function missing_reference at 0x7efbfce2d1f0> for event 'missing-reference' threw an exception (exception: not enough values to unpack (expected 2, got 1))
```

**Comment by altendky** [comment]
I haven't gone back to dig around but per my comment in the PR it seems like the exception is now avoided but the links still don't work.  If I get a chance to check this I'll follow up with the present status.
